[build]
command = "npm run build"
functions = "netlify/functions"
publish = "dist"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[env]
[env.production]
VITE_NETLIFY_FUNCTIONS_URL = "https://ortofrutta-brescia.netlify.app/.netlify/functions"
